// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZddeem-A2s68L8hd5R1tz8fltxrLOTTM',
    appId: '1:455586385995:web:484f90cde3a88ab9777dce',
    messagingSenderId: '455586385995',
    projectId: 'flutter-demo-mh',
    authDomain: 'flutter-demo-mh.firebaseapp.com',
    storageBucket: 'flutter-demo-mh.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKm3i5KrlCi-WnJZ7VxKi9rHETnLdI9yA',
    appId: '1:455586385995:android:22fc609c6dce47df777dce',
    messagingSenderId: '455586385995',
    projectId: 'flutter-demo-mh',
    storageBucket: 'flutter-demo-mh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHKUDO1Wdwdpa7ggToCFktj9arZ873cgw',
    appId: '1:455586385995:ios:a1a6ee2ba0d64382777dce',
    messagingSenderId: '455586385995',
    projectId: 'flutter-demo-mh',
    storageBucket: 'flutter-demo-mh.appspot.com',
    iosClientId: '455586385995-81n1149mpgf426getokd5f58bsgeedns.apps.googleusercontent.com',
    iosBundleId: 'com.example.appmiguelangel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHKUDO1Wdwdpa7ggToCFktj9arZ873cgw',
    appId: '1:455586385995:ios:a1a6ee2ba0d64382777dce',
    messagingSenderId: '455586385995',
    projectId: 'flutter-demo-mh',
    storageBucket: 'flutter-demo-mh.appspot.com',
    iosClientId: '455586385995-81n1149mpgf426getokd5f58bsgeedns.apps.googleusercontent.com',
    iosBundleId: 'com.example.appmiguelangel',
  );
}
